/*BVAAN - Balika Vadhu and Alok Nath
#dynamic-programming

Anandi and Jagya were getting married again when they have achieved proper age. Dadi Sa invited Alok Nath to do the kanyadaan and give blessings. Alok Nath has 2 blessings. Each bessing is in the form of a string consisting of lowercase charaters(a-z) only. But he can give only one blessing of K length because some priest told him to do so. Thus he decides to generate a blessing using the other two blessings. While doing this he wants to ensure that happiness brought into their life by his blessing is maximum.

The generated blessing is a common subsequence of length K of the two blessings he has. Happiness of the blessing he generates is calculated by the sum of ASCII values of characters in the blessing and he wants the happiness to be maximum. If he is not able to generate a common subsequence of length K then the happiness is 0 (zero). Alok Nath comes to you and asks you to find the maximum happiness that can be generated by the two blessings he has. 

Input Specification
First line consists of number of test cases t. Each test case consists of two strings b1 (blessing 1),b2 (blessing 2) and an integer K, each of them in separate lines.

Output Specification
Output consists of t lines each containing an integer denoting the maximum happiness value that can be generated by the two blessings.

Constraint
1 <= t <= 50
1 <= length(b1) , length(b2) <= 100 
1 <= K <= 100

Sample Input
2
asdf
asdf
3
anandi
jagya
3

Sample Output
317
0

*/

#include <algorithm>
#include <iostream>
#include <string>
#include <vector>

// Recurrence relation
int solve_recursive(const std::string& str1, int pos1, const std::string& str2, int pos2, int k)
{
    if (pos1 == 0 || pos2 == 0 || k == 0) 
        return 0;
    else if (str1[pos1-1] == str2[pos2-1])
        return std::max(str1[pos1-1] + solve_recursive(str1, pos1 - 1, str2, pos2 - 1, k - 1), 
                        solve_recursive(str1, pos1 - 1, str2, pos2 - 1, k));
    else
        return std::max(solve_recursive(str1, pos1 - 1, str2, pos2, k), 
                        solve_recursive(str1, pos1, str2, pos2 - 1, k));
}


// Solve with Dynamic Programming bottom-up approach
int solve(const std::string& str1, const std::string& str2, int k)
{
    const int sz1 = str1.size(), sz2 = str2.size();
    
    std::vector<std::vector<std::vector<int>>> dp (sz1+1, std::vector<std::vector<int>>(sz2+1, std::vector<int>(k+1)));
        
    // Fill table according to recurrence relation expressed above
    for (int x = 0; x <= sz1; ++x)
    {
        for (int y = 0; y <= sz2; ++y)
        {
            for (int z = 0; z <= k; ++z)
            {
                if (x == 0 || y == 0 || z == 0)
                    dp[x][y][z] = 0;
                else if (str1[x-1] == str2[y-1])
                    dp[x][y][z] = std::max(str1[x-1] + dp[x-1][y-1][z-1], dp[x-1][y-1][z]);
                else
                    dp[x][y][z] = std::max(dp[x-1][y][z], dp[x][y-1][z]);
            }
        }
    }
    
    // Iterate table to check constraint LCS == k
    // Or better: Every k change must be a char insertion
    // Or else the result is invalid
    int x = sz1, y = sz2, z = k;
    
    while (x > 0 && y > 0 && z > 0)
    {
        if (str1[x-1] == str2[y-1])
        {
            if (str1[x-1] + dp[x-1][y-1][z-1] > dp[x-1][y-1][z])
            {
                --z;
            }
            
            --x;
            --y;
        }
        else if (dp[x-1][y][z] > dp[x][y-1][z])
            --x;
        else
            --y;
    }
        
    return z > 0 ? 0: dp[sz1][sz2][k];
}

int main()
{
    int tests;
    std::cin >> tests;
    
    while (tests--)
    {
        std::string a, b;
        int k;
        
        std::cin >> a >> b >> k;
        
        //std::cout << solve_recursive(a, a.size(), b, b.size(), k) << std::endl;
        std::cout << solve(a, b, k) << std::endl;
    }
    
    return 0;
}
